version: 2

sources:
  - name: stg
    schema: stg
    tables:
      - name: raw_flight_data
        description: Raw flight state vectors from OpenSky
        columns:
          - name: icao24
          - name: time_position
          - name: latitude
          - name: longitude
          - name: velocity
          - name: heading_deviation
          - name: geo_altitude
          - name: vertical_rate
          - name: baro_altitude

      - name: raw_weather_data
        description: Raw weather observations from Open-Meteo
        columns:
          - name: latitude
          - name: longitude
          - name: temperature
          - name: humidity
          - name: temperature_2m
          - name: cloud_cover
          - name: cloud_cover_low
          - name: cloud_cover_mid
          - name: cloud_cover_high
          - name: pressure_msl
          - name: surface_pressure
          - name: precipitation
          - name: wind_speed_10m
          - name: wind_speed_80m
          - name: wind_speed_120m
          - name: wind_speed_180m
          - name: wind_direction_10m
          - name: wind_direction_80m
          - name: wind_direction_120m
          - name: wind_direction_180m
          - name: wind_gusts_10m
          - name: temperature_80m
          - name: temperature_120m
          - name: temperature_180m
